### ISSUE TITLE
Feature/Research: yarn|npm file production list instead of install

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/serverless-jetpack#24]
`serverless-webpack` does an interesting thing of just listing production dependencies.

## Task

- [ ] Research if this is enough info to skip a real install
- [ ] _Note_: This is the abstract dependency tree, not what's on disk. Probably would need disk i/o to traverse up and recreate the concrete installed tree.
- [ ] Implement a POC and see if timing is better!

## Notes
- `NODE_ENV=production yarn list --json`
- `npm ls --production --json`

**Comment by ryan-roemer** [comment]
## Status / Research

Can get and exclude a list of patterns from `yarn list` and in about as much time as the existing `yarn install` approach, **but** the list results appear incorrect, not completely filtering out devDependencies.

Here, in relevant part the **root** `node_modules/prop-types` dep is a devDep from `next` and shouldn't be in this list:

```
~/scm/fmd/serverless-jetpack/test/packages/huge/yarn $ NODE_ENV=production yarn list --prod
yarn list v1.2.1
# ...
├─ prop-types@15.7.2        # WHITE: Should not be here.
│  ├─ loose-envify@^1.4.0
│  ├─ object-assign@^4.1.1
│  └─ react-is@^16.8.1
# ...
├─ react-dom@16.8.6         # GRAY: Should be white (concrete on disk).
│  ├─ loose-envify@^1.1.0
│  ├─ object-assign@^4.1.1
│  ├─ prop-types@^15.6.2
│  └─ scheduler@^0.13.6
├─ react-is@16.8.6
├─ react@16.8.6             # GRAY: Should be white (concrete on disk).
│  ├─ loose-envify@^1.1.0
│  ├─ object-assign@^4.1.1
│  ├─ prop-types@^15.6.2
│  └─ scheduler@^0.13.6
# ...
✨  Done in 0.80s.
```

**Comment by ryan-roemer** [comment]
Superseded by https://github.com/FormidableLabs/serverless-jetpack/pull/28
