### ISSUE TITLE
Feature: Support yarn workspaces with linked dependencies.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/serverless-jetpack#26]
## Scenario

We can have something like:

```js
// package.json (ROOT)
{
  "private": true,
  "name": "ROOT",
  "version": "VERSION",
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  },
  "dependencies": {
    // ...
  },
  "devDependencies": {
    // ...
  }
}

// packages/server/package.json
{
  "name": "server",
  "version": "VERSION",
  "main": "src/index.js",
  "dependencies": {
    // ...
    "serverless-http": "^1.9.1",
    "shared": "^1.1.0"
  }
}


// packages/shared/package.json
{
  "name": "shared",
  "version": "VERSION",
  "dependencies": {
    // ...
  }
}
```

Normally, `yarn` will do a symlink in `packages/server/node_modules/shared` to point to `packages/shared`. But `jetpack` is going to just copy the package json to a separate directory and yarn install without reference to the workspace.

## Task
- [ ] Try to cobble together a scenario
- [ ] Choose best solution

## Potential issues
- [ ] Hoisting of dependencies down to root.
- [ ] `devDependencies` in a shared dep from `packages/*/package.json` that we want to exclude from the build.

## Ideas / potential solutions
- [ ] "Roots" to do `inspectdep` inference on as an option.

/cc @jjasonclark

**Comment by ryan-roemer** [comment]
Should be fixed by https://github.com/FormidableLabs/serverless-jetpack/pull/28
