### ISSUE TITLE
Serverless 3 Umbrella

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/serverless-jetpack#292]
## Plan
- [ ] Only integrate with serverless 3+
    - [ ] Handle all warnings
- [ ] Use `trace-pkg`
    - [ ] Will need to expose glob library. Consider a refactor/abstraction of glob library first because of ESM issues.
- [ ] Remove benchmarks / big test scenarios
- [ ] Consider removing `inspectdep` / legacy mode altogether (or ticket for later re-introduction)
- [ ] Definitely semver major

## Tasks

- [ ] Close out all old tickets

**Comment by jeanbmar** [comment]
Hey @ryan-roemer, you might want to have a look at this https://github.com/npm/cli/pull/4082 if you plan to change packaging in the future.
I'm using for non-serverless projects and its pretty good. Hopefully it will land in npm.

**Comment by ryan-roemer** [comment]
@jeanbmar Cool! that's an option if we keep legacy mode as a potential replacement for our [inspectdep](https://github.com/FormidableLabs/inspectdep) library if it's faster.

Either approach is going to likely be slower and definitely produce large bundles than Jetpacks `trace` mode -- out of curiosity, have you tried `trace` mode for faster, smaller Lambda bundles?

**Comment by jeanbmar** [comment]
I haven't tried it, at least not yet.
I was worried of possible subtile side-effects at the time I looked at it so I just went with the default packaging :).

**Comment by jeanbmar** [comment]
> Hey @ryan-roemer, you might want to have a look at this [npm/cli#4082](https://github.com/npm/cli/pull/4082) if you plan to change packaging in the future. I'm using for non-serverless projects and its pretty good. Hopefully it will land in npm. Btw love this tool thanks!

In addition, it wwould solve collapsed dependencies issues since npm copy installs conflicting dependencies in the right subdirectories.
